print("Guess Game")
print("I have a number between 1-100")
print("You have 10 tries to guess.")

import random
#Create a variable to store the number generated by the computer.
#currently the number is always set to 76.
number = 76

#Generate a random  number between 1 and 100
#number = random.randint(1,100)
#Keep a track of the number of tries by the user
tries = 0

#Use binary search approach to win the game in the minimum no. of tries.

#Allow the user a maximum of 10 tries
while tries <=10:
#In each try, ask the user to enter their guess
    tries += 1
    print("Try no. " + str(tries))
    guess = int(input("Enter your guess:"))

#If the guess matches the number, show the number of tries taken to get it right.
#Game ends.
#use the appropriate message to show if the tries are greater than 1.
    if guess == number:
        win = "You guessed correctly in "+ str(tries) + " try." if (tries == 1) else "You guessed correctly in "+ str(tries) + " tries."
        print(win)
        break
#If the guess is smaller than the number, prompt the user again
    elif guess < number:
        print("Your guess is low.")
#If the guess is larger than the number, prompt the user again.
    elif guess > number:
        print("Your guess is high.")